config/routes.rb
Rails.application.routes.draw do

  resource :admin_panel
  root to: "home#index"

  devise_for :users, :path_prefix => 'my'

  resources :users
  resources :import_politicians


  resources :votes
  resources :propositions
  #resources :terms # Removed due to new terms flow
  resources :offices
  resources :parishes

  resources :notices do
  collection do
    get :manage
  end
end

resources :politicians do
  collection do
    get :manage
  end
end

  get 'import/index'
  get 'import_props/index'
  get 'import_terms/index'
  get 'import_terms/show'
  get 'terms', to: 'terms#index'
  get 'terms/:parish_id/:year', to: 'terms#show', as: :terms_by_parish_year
  get 'import/index'
  get 'home/index'
  get 'notices/index'
  get 'offices/index'
  get 'politicians/index'
  get 'propositions/index'
  get 'search', to: 'search#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'termsandconditions' , to: 'static_pages#tandc'
  post 'politicians/:id(.:format)', to:'politicians#restore'

end

app/models/parish.rb
class Parish < ApplicationRecord
  has_many :terms
  has_many :politicians, -> { with_deleted }

  def parish_desc
      if self.name == 'Saint Helier'
        "St Helier has a population of about 33,500, roughly 34.2% of the total population of Jersey, and is the capital of the Island (although Government House is situated in St Saviour). The urban area of the parish of St Helier makes up most of town, although some of the town area is situated in adjacent St Saviour, with suburbs sprawling into St Lawrence and St Clement. The greater part of St Helier is rural.

        The parish covers a surface area of 4.1 square miles (10.6 km2), being 9% of the total land area of the Island (this includes reclaimed land area of 494 acres (2.00 km2) or 200 ha).
        Saint Helier is the most populated of Jerseys' parishes, with 33,522 residents according to the 2011 census.
        With the Constable, the parish therefore has 11 representatives in the States of Jersey (out of 53 elected members).
        The Parish also has its own responsibilities and elections to the Municipality of St Helier take place to elect honorary officials who fulfill a variety of roles for Parishioners under the overall control of the Constable, two Procureurs du Bien Public and the Parish Assembly."
      elsif self.name == 'Grouville'
        'Grouville is in the south east of the island and is dominated by the broad sweep of the Royal Bay of Grouville. The parish covers a surface area of 4,354 vergées (7.8 km²). It borders Saint Clement, Saint Saviour and Saint Martin.
        Population: 4,866 (2011)'
      elsif self.name == 'Saint Brelade'
        'Saint Brélade population is around 9,560, and it occupies the southwestern part of the island. It is the only parish to border only one other parish, Saint Peter. The parish is the second-largest parish by surface area, covering 7,103 vergées (3,157 acres or 12.78 km²), which is 11% of the total land surface of the island.
        Its name is derived from a 6th-century Celtic or Welsh "wandering saint" named Branwalator or Saint Brelade (also Branwallder, Broladre, Brelodre, Brélade), who is said to have been the son of the Cornish king, Kenen. He is also said to have been a disciple of Samson of Dol, and worked with this churchman in Cornwall and the Channel Islands. A large section of the Jersey Railway linking La Corbière with Saint Helier ran through the parish between 1870 and 1936.
        Saint Brélade has some of the most popular bays in Jersey, with Saint Brélades Bay, Ouaisné, Portelet and parts of both Saint Ouens Bay and Saint Aubins Bay falling within the parish boundaries. The village (or town) of Saint Aubin was originally a fishing port facing Saint Helier on the opposite side of Saint Aubins Bay. Saint Aubin was historically the main centre of population in the parish, but residential development at Les Quennevais has shifted that centre of population.'
      elsif self.name == 'Saint Clement'
        'Saint Clement (Jèrriais: St Cliément) is in the south east of the Island, and contains some of the suburbs of Saint Helier. It is the smallest parish by surface area, but the second most densely populated.  Saint Clement stretches west to east from Le Dicq to within a quarter mile of La Rocque harbour (at the end of Rue de la Lourderie). Its surface area is around 1,044 acres (4.22 km2).
        Aside from the two deputies who sit in the States of Jersey and represent the parish, Saint Clement also has its own local administration. This, like each of the other eleven parishes, is made up of a Connétable (often referred to as the "father" of the parish), who is elected for a three-year term and has a seat in the States Chamber, and on the Comité des Connétables; two Procureurs du Bien Public, who are also elected and oversee the finances of the parish; a Recteur (or Rector), responsible for the parish church; members of the parish Honorary Police (made up of Centeniers, Vingteniers and Constables Officers); and other officers such as churchwardens, roads inspectors, rates assessors and a registrar.
        Population	9,221 (2011).'
      elsif self.name == 'Saint John'
        'Saint John shares borders with Saint Mary on its west, Trinity to the east, and Saint Lawrence and Saint Helier on its south.
        The cliffs of the north coast afford some of the best views in Jersey. After Trinity, it has the second highest point in Jersey at Mont Mado (473 ft). The parish covers territory of 4,846 vergées (8.7 km².).
        The Centre Stone at Sion in St. John is traditionally regarded as the centre of the Island although it is far from the geographic centre by modern calculations. The stone is prehistoric, showing evidence of cup marks, and may have been brought from a nearby dolmen now vanished.
        Population 2,911 (2011).'
      elsif self.name == 'Saint Lawrence'
        'Saint Lawrence (Jèrriais: St Louothains). The parish covers 5,258 vergées (9.5 km², (3.7 sq mi)) and occupies the centre of the Island.
        Much of the parish is inland, though it has a short stretch of coastline in Saint Aubins Bay. It borders Saint Peter and Saint Mary to the west, Saint John to the north and east, and Saint Helier to the east.
        Including the Connétable, the parish has three elected representatives in the States of Jersey.
        Area	9.5 km2
        Population	5,418 (2011).'
      elsif self.name == 'Saint Martin'
        'Saint Martin (Jèrriais: St Martîn). Historically it was called "Saint Martin le Vieux" to distinguish it from the present day parish of Grouville.
        Saint Martin is the only parish in Jersey not to conduct its municipal business from a Parish Hall. Saint Martin has a Public Hall instead, having accepted money from the States of Jersey to provide an assembly room.
        This is one of the most agricultural parishes, and one of the most sought after places to live in the island. It has the best herd of Jersey cattle, some of the largest potato growers and a number of small farmers now cultivating the new “Genuine Jersey”, mainly organic, brand.
        Area 10.3 km2 (4.0 sq mi)
        Density	370/km2 (950/sq mi)
        Population	3,763 (2011)'
      elsif self.name == 'Saint Mary'
        'Saint Mary (Jèrriais: Sainte Mathie). It is situated in the north west and covers an area of 3,604 vergées (6.5 km²).
        It borders four other parishes: Saint Ouen, Saint John, Saint Peter and Saint Lawrence. The parish and its eponymous church derive their name from a medieval monastery, probably destroyed during Viking raids some time between the 8th and 10th centuries. In 1042 Duke William gave "Saint Mary of the Burnt Monastery" to the abbey of Cerisy.
        Population 1,752 (2011)
        Density	270/km2 (700/sq mi)'
      elsif self.name == 'Saint Ouen'
        'Saint Ouen (Jèrriais: Saint Ouën). It is in the north west of Jersey. The parish is the largest parish by surface area, covering 8,341 vergées (15 km²).
        It is reputed to be the most traditional of the parishes, being the farthest from Saint Helier and with much of the territory of the parish forming a peninsula. Its manor, Saint Ouens Manor has been the seat of the de Carteret family for over eight centuries.
        The traditional nickname for St. Ouennais is Gris Ventres (grey bellies) - a reference to the custom of men from the parish to wear jerseys of undyed wool, which distinguished them from men from other parishes who generally wore blue.
        Area	15 km2 (6 sq mi)
        Population	4,097 (2011)
        Density	270/km2 (710/sq mi).'
      elsif self.name == 'Saint Peter'
        'Saint Peter (Jèrriais: St Pièrre) is in the west central part of the island. It is the only parish with two separate coastlines, stretching from Saint Ouens Bay in the west to Saint Aubins Bay in the south, and thereby cutting Saint Brelade off from other parishes. The parish is the fourth-largest parish by surface area, covering 6,469 vergées (11.6 km2 (4.5 sq mi).
        It borders four other parishes.
        The traditional nickname for St. Pierrais is ventres à baînis (limpet bellies), perhaps because their parish sticks to two coasts like limpets.
        Area 11.6 km2 (4.5 sq mi)
        Population 5,003 (2011)
        Density	430/km2 (1,100/sq mi).'
      elsif self.name == 'Saint Saviour'
        'Saint Saviour (Jèrriais: St Saûveux/St Sauveur) has a land surface area of 3.6 square miles (9.3 km2), borders with five other parishes and has a very small coastline at Le Dicq.
        Total area	9.3 km2 (3.6 sq mi)
        Population	13,580 (2011)
        Density	1,500/km2 (3,800/sq mi).'
      elsif self.name == 'Trinity'
        'Trinity (French: La Trinité, Jèrriais: La Trinneté) is located the north east of the island.
        Trinity has the reputation of being the most rural of Jerseys parishes, being the third-largest parish by surface area with the third-smallest population. The parish covers 6,817 vergées (12.3 km2 (4.7 sq mi)). It is home to the States Farm, the Durrell Wildlife Park at Les Augrès Manor, the headquarters of the Royal Jersey Agricultural and Horticultural Society at the Royal Jersey Showground, and the Pallot Heritage Steam Museum.
        Total area	12.3 km2 (4.7 sq mi)
        Population 3,156 (2011)
        Density	260/km2 (660/sq mi).'
      elsif self.name == 'Island Wide'
        'Senators represent the whole Island. All 8 Senators are elected for the same term of office as the Constables and Deputies.'
      else
        'Parish'
      end
    end
end

app/controllers/parishes_controller.rb
class ParishesController < ApplicationController
  before_action :set_parish, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /parishes
  # GET /parishes.json
  def index
    @parishes = Parish.all
  end

  # GET /parishes/1
  # GET /parishes/1.json
  def show
  end

  # GET /parishes/new
  def new
    @parish = Parish.new
  end

  # GET /parishes/1/edit
  def edit
  end

  # POST /parishes
  # POST /parishes.json
  def create
    @parish = Parish.new(parish_params)

    respond_to do |format|
      if @parish.save
        format.html { redirect_to @parish, notice: 'Parish was successfully created.' }
        format.json { render :show, status: :created, location: @parish }
      else
        format.html { render :new }
        format.json { render json: @parish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parishes/1
  # PATCH/PUT /parishes/1.json
  def update
    respond_to do |format|
      if @parish.update(parish_params)
        format.html { redirect_to @parish, notice: 'Parish was successfully updated.' }
        format.json { render :show, status: :ok, location: @parish }
      else
        format.html { render :edit }
        format.json { render json: @parish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parishes/1
  # DELETE /parishes/1.json
  def destroy
    @parish.destroy
    respond_to do |format|
      format.html { redirect_to parishes_url, notice: 'Parish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parish
      @parish = Parish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parish_params
      params.require(:parish).permit(:name)
    end
end

app/helpers/parishes_helper.rb
module ParishesHelper
end

app/views/parishes/_form.html.erb
<%= form_with(model: parish, local: true) do |form| %>
  <% if parish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parish.errors.count, "error") %> prohibited this parish from being saved:</h2>

      <ul>
      <% parish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :parish_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parishes/edit.html.erb
<h1>Editing Parish</h1>

<%= render 'form', parish: @parish %>

<%= link_to 'Show', @parish %> |
<%= link_to 'Back', parishes_path %>

app/views/parishes/index.html.erb
<!-- Bringing in jQuery and Masonry libraries -->

<div class="parish_container">
  <div id="accordion" role="tablist">
    <% @parishes.each do |parish| %>
    <div class="card">
      <div class="card-header" role="tab" id="headingOne">
          <h5 class="mb-0">
            <a data-toggle="collapse" data-target="#collapse-<%= parish.id %>" href="#collapse-<%= parish.id %>" aria-expanded="true" aria-controls="collapse">
              <%= parish.name %>
            </a>
        </h5>
      </div>
      <div id="collapse-<%= parish.id %>" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
        <div class="container parish">
          <div class="row">
            <div class="col-6 parish_desc">
              <%= parish.parish_desc %>
              <% if !current_user.blank? && current_user.role_id == 1 %>
                      <div class="manage_container">
                        <%= link_to 'Edit', edit_parish_path(parish),class:"btn btn-primary manage_button" %>
                        <%= link_to 'Delete', parish, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-primary manage_button" %>
                      </div>
                      <%end%>
            </div>
            <div class="col-6">
              <% 
                politicians = parish.politicians.where(in_term:1)
                politicians.each do |politician| %>
              <div class="card-body">
                <div class="row">
                  <div class="col-3">
                    <span class="parish_politician_title">
                      <%= politician.title %>
                    </span>
                  </div>
                  <div class="col-9">
                    <span class="parish_politician">
                      <%= link_to politician.full_name, politician_path(politician)  %>
                    </span>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>

      </div>
    </div>
    <% end %>
  </div>
  <div class="district_container">
    <a class="district_link" href="https://cab.org.je/index.php?option=com_content&view=article&id=221:electoral-districts-731l1&catid=29&Itemid=53" target="_blank">
    WHATS MY DISTRICT?
    </a>

    <p>If you live in St. Helier, St. Saviour or St. Brelade, you may need to know which district you reside in. </p>
  </div>

  <br>

  <% if !current_user.blank? && current_user.role_id == 1 %>
      <%= link_to 'New Parish', new_parish_path, class:"btn btn-primary" %>

  <% end %>

</div>

app/views/parishes/new.html.erb
<h1>New Parish</h1>

<%= render 'form', parish: @parish %>

<%= link_to 'Back', parishes_path %>

app/views/parishes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @parish.name %>
</p>

<div class="manage_container">
  <% if !current_user.blank? && current_user.role_id == 1 %>
      <%= link_to 'Edit', edit_parish_path(@parish), class:"btn btn-primary manage_button" %>
      <%= link_to 'Delete', @parish, method: :delete, data: { confirm: 'Are you sure?'}, class:"btn btn-primary manage_button" %>
<%end%>
  <%= link_to 'Back', parishes_path, class:"btn btn-primary manage_button" %>
</div>