config/routes.rb
Rails.application.routes.draw do

  resource :admin_panel
  root to: "home#index"

  devise_for :users, :path_prefix => 'my'

  resources :users
  resources :import_politicians


  resources :votes
  resources :propositions
  #resources :terms # Removed due to new terms flow
  resources :offices
  resources :parishes

  resources :notices do
  collection do
    get :manage
  end
end

resources :politicians do
  collection do
    get :manage
  end
end

  get 'import/index'
  get 'import_props/index'
  get 'import_terms/index'
  get 'import_terms/show'
  get 'terms', to: 'terms#index'
  get 'terms/:parish_id/:year', to: 'terms#show', as: :terms_by_parish_year
  get 'import/index'
  get 'home/index'
  get 'notices/index'
  get 'offices/index'
  get 'politicians/index'
  get 'propositions/index'
  get 'search', to: 'search#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'termsandconditions' , to: 'static_pages#tandc'
  post 'politicians/:id(.:format)', to:'politicians#restore'

end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]
load_and_authorize_resource
  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.order('created_at DESC')
  end


  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = current_user.notices.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.delete
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:user_id, :title, :content)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<div class="containter-fluid jumbotron" style="width:70%;margin:auto;">
<div class="form-group">
<%= form_with(model: notice, local: true, class:"form-horizontal") do |form| %>
  <% if notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
     <%= form.label :title, class: "col-sm-2 control-label" %>
     <div class="col-sm-10">
        <%= form.text_field :title, class: "form-control" %>
     </div>


     <div class="form-group">
        <%= form.label :content, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
           <%= form.text_area :content, class: "form-control",style: "min-height:300px;"%>
        </div>


<div class="manage_container">
    <button type="submit" class="btn btn-success manage_button"> Submit</button>
  </div>
</div>
</div>
</div>
<% end %>

app/views/notices/_notice_home.html.erb
<div class="card text-white bg-primary mb-3">
    <div class="card-header">
      <h4><%= link_to notice.title,notice %></h4>
      <div class="home_notice_author">
        <i>Written by  <%= notice.user.username %> - <%= notice.created_at.strftime("%d %b. %Y") %> </i>
      </div>
    </div>
    <div class="card-body text-primary bg-white">
    <div class="card-text">
	<%= truncate notice.content, length: 260 %>
	<%= link_to 'read more', notice %> 
    </div></div>

    <% if !current_user.blank? && current_user.role_id == 1 %>
            <div class="manage_container">
              <%= link_to 'Edit', edit_notice_path(notice),class:"btn btn-primary manage_button" %>
              <%= link_to 'Delete', notice, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-primary manage_button" %>
            </div>

    <% end %>
</div>

app/views/notices/edit.html.erb
<div class="page_title"><h1> Edit Notice</h1> </div>

<%= render 'form', notice: @notice %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<div class="notice_wrapper">
    <% @notices.each do |notice| %>
    <%= render 'notice_home', notice: notice %>
    <% end %>
</div>

<br>
  <% if !current_user.blank? && current_user.role_id == 1 %>
      <%= link_to 'New Notice', new_notice_path, class:"btn btn-primary" %>
  <% end %>

app/views/notices/manage.html.erb
<h1> Notice Management </h1>
<br>
  <%= link_to 'Return to Admin Panel', admin_panel_path%>
</br>
<div class="table-responsive">
  <table class="table table-hover">
    <tr>
      <th> Post Title </th>
      <th> Notice Author </th>
      <th> Notice Date <th>
        <th></th>
        <th></th>
    </tr>
    <% @notices.each do |notice| %>
  <tr>
    <td><%= notice.title %> </td>
    <td><%= notice.user.username %> </td>
    <td><%= notice.created_at.strftime("%d %b. %Y") %></td>
    <td><%=link_to "View Full Notice",  notice %></td>
    <td><%= link_to 'Edit', edit_notice_path(notice)%></td>
    <td>  <%= link_to 'Delete', notice, method: :delete, data: { confirm: 'Are you sure?' }%></td>
  </tr>
  <%end%>
  </table>
</div>

app/views/notices/new.html.erb
<div class="page_title"><h1> New Notice</h1> </div>

<%= render 'form', notice: @notice %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<div class="notice_container">
    <div class="notice_title">
      <%= @notice.title %>
    </div>
    <div class="notice_author">
      <i>Written by  <%= @notice.user.username %> - <%= @notice.created_at.strftime("%d %b. %Y") %> </i>
    </div>
    <divc class="notice_content">
      <%= @notice.content %>
    </div>


  <div class="manage_container">
  <% if !current_user.blank? && current_user.role_id == 1 %>
      <%= link_to 'Edit', edit_notice_path(@notice),class:"btn btn-primary manage_button" %>
      <%= link_to 'Delete', @notice, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-primary manage_button" %>
  <% end %>
    <%= link_to 'Back', notices_path,class:"btn btn-primary manage_button" %>
  </div>
</div>