config/routes.rb
Rails.application.routes.draw do

  resource :admin_panel
  root to: "home#index"

  devise_for :users, :path_prefix => 'my'

  resources :users
  resources :import_politicians


  resources :votes
  resources :propositions
  #resources :terms # Removed due to new terms flow
  resources :offices
  resources :parishes

  resources :notices do
  collection do
    get :manage
  end
end

resources :politicians do
  collection do
    get :manage
  end
end

  get 'import/index'
  get 'import_props/index'
  get 'import_terms/index'
  get 'import_terms/show'
  get 'terms', to: 'terms#index'
  get 'terms/:parish_id/:year', to: 'terms#show', as: :terms_by_parish_year
  get 'import/index'
  get 'home/index'
  get 'notices/index'
  get 'offices/index'
  get 'politicians/index'
  get 'propositions/index'
  get 'search', to: 'search#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'termsandconditions' , to: 'static_pages#tandc'
  post 'politicians/:id(.:format)', to:'politicians#restore'

end

app/models/admin_panel.rb
class AdminPanel < ApplicationRecord
end

app/controllers/admin_panels_controller.rb
class AdminPanelsController < ApplicationController
  load_and_authorize_resource



  # GET /admin_panels/1
  # GET /admin_panels/1.json
  def show
  end

end

app/helpers/admin_panels_helper.rb
module AdminPanelsHelper
end

app/views/admin_panels/show.html.erb
<h1>Admin Panel</h1>
<div class="admin_panel_wrapper">
  <div class="card border-primary mb-3" style="max-width: 30rem;">
    <div class="card-body">

    <%= link_to 'Create New User', new_user_path, class:"btn btn-primary" %>
    <%= link_to 'Manage Users', users_path, class:"btn btn-primary" %>
    <hr>
    <%= link_to 'Create New Notice', new_notice_path, class:"btn btn-primary"%>
    <%= link_to 'Manage Notices', manage_notices_path, class:"btn btn-primary" %>
    <hr>
    <%= link_to 'Create New Politician', new_politician_path, class:"btn btn-primary"%>
    <%= link_to 'Manage Politicians', manage_politicians_path, class:"btn btn-primary"%>

    </div>
  </div>
</div>