config/routes.rb
Rails.application.routes.draw do

  resource :admin_panel
  root to: "home#index"

  devise_for :users, :path_prefix => 'my'

  resources :users
  resources :import_politicians


  resources :votes
  resources :propositions
  #resources :terms # Removed due to new terms flow
  resources :offices
  resources :parishes

  resources :notices do
  collection do
    get :manage
  end
end

resources :politicians do
  collection do
    get :manage
  end
end

  get 'import/index'
  get 'import_props/index'
  get 'import_terms/index'
  get 'import_terms/show'
  get 'terms', to: 'terms#index'
  get 'terms/:parish_id/:year', to: 'terms#show', as: :terms_by_parish_year
  get 'import/index'
  get 'home/index'
  get 'notices/index'
  get 'offices/index'
  get 'politicians/index'
  get 'propositions/index'
  get 'search', to: 'search#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'termsandconditions' , to: 'static_pages#tandc'
  post 'politicians/:id(.:format)', to:'politicians#restore'

end

app/models/politician.rb
class Politician < ApplicationRecord
acts_as_paranoid

  has_many :propositions
  has_many :votes
  has_many :terms
  belongs_to :parish

  def self.search(query)
    if query.blank?  # blank? covers both nil and empty string
      all
    else
      where('full_name LIKE ?', "%#{query}%")
    end
  end
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
  before_action :set_politician, only: [:show, :edit, :update, :destroy, :undelete]
## load_and_authorize_resource
  # GET /politicians
  # GET /politicians.json

  def index
    @politicians = Politician.where(in_term:1)
    @politicians_grouped = @politicians.group_by(&:title)
  end

def manage
  @politicians = Politician.all
end
  # GET /politicians/1
  # GET /politicians/1.json
  def show
	@votes_pagination = @politician.votes.order("id DESC").paginate(:page => params[:page])
  end
  # GET /politicians/new
  def new
    @politician = Politician.new
  end

  # GET /politicians/1/edit
  def edit
  end

  # POST /politicians
  # POST /politicians.json
  def create
    @politician = Politician.new(politician_params)

    respond_to do |format|
      if @politician.save
        format.html { redirect_to @politician, notice: 'Politician was successfully created.' }
        format.json { render :show, status: :created, location: @politician }
      else
        format.html { render :new }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /politicians/1
  # PATCH/PUT /politicians/1.json
  def update
    respond_to do |format|
      if @politician.update(politician_params)
        format.html { redirect_to @politician, notice: 'Politician was successfully updated.' }
        format.json { render :show, status: :ok, location: @politician }
      else
        format.html { render :edit }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /politicians/1
  # DELETE /politicians/1.json
  def destroy
      @politician.destroy
      respond_to do |format|
        format.html { redirect_to politicians_url, notice: 'Politician was successfully Archived.' }
        format.json { head :no_content }
      end
    end

    def restore
      @politician = Politician.with_deleted.find(params[:id])
      @politician.restore
        respond_to do |format|
        format.html { redirect_to manage_politicians_path, notice: 'Politician was successfully restored.' }
        format.json { head :no_content }
      end
    end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_politician
      if !current_user.blank? && current_user.role.name == "Admin"
        @politician = Politician.with_deleted.find(params[:id])
      else
        @politician = Politician.without_deleted.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def politician_params
    params.fetch(:politician, {})
    params.permit(:deleted_at)
    end
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/views/politicians/_form.html.erb
<div class="container-fluid jumbotron" style="width:70%;">
   <div class="form-group">
      <%= form_with(model: politician, local: true, class: "form-horizontal") do |form| %>
      <% if politician.errors.any? %>
      <div id="error_explanation">
         <h2><%= pluralize(politician.errors.count, "error") %> prohibited this politician from being saved:</h2>
         <ul>
            <% politician.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
         </ul>
      </div>
      <% end %>
      <div class="form-group">
         <%= form.label :full_name, class: "col-sm-2 control-label" %>
         <div class="col-sm-10">
            <%= form.text_field :full_name, class: "form-control" %>
         </div>
         <div class="form-group">
            <%= form.label :title, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
               <%= form.text_field :title, class: "form-control" %>
            </div>
         </div>
         <div class="form-group">
            <%= form.label :address, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
               <%= form.text_area :address, class: "form-control" %>
            </div>
         </div>
         <div class="form-group">
            <%= form.label :summary, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
               <%= form.text_area :summary, class: "form-control" %>
            </div>
         </div>
         <div class="form-group">
            <%= form.label :avatar, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
               <%= form.text_field :avatar, class: "form-control" %>
            </div>
         </div>
         <div class="form-group">
            <%= form.label :mobile, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
               <%= form.text_field :mobile, class: "form-control" %>
            </div>
         </div>
         <div class="form-group">
            <%= form.label :fax, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
               <%= form.text_field :fax, class: "form-control" %>
            </div>
         </div>
         <div class="form-group">
            <%= form.label :landline, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
               <%= form.text_field :landline, class: "form-control" %>
            </div>
         </div>
         <div class="form-group">
            <%= form.label :parish, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
               <%= form.text_field :parish_id, class: "form-control" %>
            </div>
         </div>


      </div>
      <div class="form-group">
         <%= form.submit "Update Politician", class: "btn btn-default" %>
      </div>
      <% end %>
   </div>
</div>

app/views/politicians/edit.html.erb
<h1>Editing Politician</h1>

<%= render 'form', politician: @politician %>

<%= link_to 'Show', @politician %> |
<%= link_to 'Back', politicians_path %>

app/views/politicians/index.html.erb
<div class="container">
   <div class="politician_list">
      <div class="row">
         <% @politicians_grouped.each do |title, politicians| %>
           <% politicians.each do |politician| %>
           <div class="col no-flex-grow">
              <div class="card card--fixed-width">
                  <%
                    url = URI.unescape(politician.avatar.gsub "http://www.statesassembly.gov.je/SiteCollectionImages/States%20Members/", "")
                  %>
                 <div class="politician_avatar" style="background-image: url('<%= image_path(url) %>');"></div>
                 <div class="card-body">
                    <h4 class="card-title">
                      <%= link_to politician do %>
                        <%= politician.full_name %>
                      <% end %>
                    </h4>
                    <h6 class="card-subtitle text-muted"><%= politician.parish.name %></h6>
                 </div>
                 <div class="card-footer"><%= title %></div>
              </div>
           </div>
           <% end %>
         <% end %>
      </div>
   </div>
</div>

<% if !current_user.blank? && current_user.role_id == 1 %>
    <%= link_to 'New Politician', new_politician_path, class:"btn btn-primary"%>
<% end %>

app/views/politicians/manage.html.erb
<h1> Politician Management </h1>
<br>
  <%= link_to 'Return to Admin Panel', admin_panel_path%>
<br>
<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead class="break active"><td class="theader"colspan="7">Active Politicians</td></tr>
    <thead class="mng_tbl_head active">
      <th data-field="first_name" sortable="true">First Name</th>
      <th>Last Name</th>
      <th>Title</th>
      <th>Email<th>
        <th></th>
        <th></th>
    </thead>
    <% @politicians.without_deleted.each do |politician| %>
  <tr class="mng_tbl_row">
    <td class="filterable-cell"><%= politician.first_name%></td>
    <td class="filterable-cell"><%= politician.last_name%></td>
    <td class="filterable-cell"><%= politician.title%> </td>
    <td class="filterable-cell"><%= politician.email%></td>
    <td class="filterable-cell"><%= link_to 'More info', politician%></td>
    <td class="filterable-cell"><%= link_to 'Edit', edit_politician_path(politician)%></td>
    <td class="filterable-cell"><%= link_to 'Archive', politician, method: :destroy, data: { confirm: 'Are you sure?' }%></td>
  </tr>

  <%end%>
  <tr class="break"></tr>
  <thead class="break deleted"><td class="theader"colspan="7">Archived Politicians</td></tr>
  <thead class="mng_tbl_head deleted">
    <th data-field="first_name" sortable="true">First Name</th>
    <th>Last Name</th>
    <th>Title</th>
    <th>Email<th>
      <th></th>
      <th></th>
  </thead>
  <% @politicians.only_deleted.each do |politician| %>
<tr class="mng_tbl_row">
  <td class="filterable-cell"><%= politician.first_name%></td>
  <td class="filterable-cell"><%= politician.last_name%></td>
  <td class="filterable-cell"><%= politician.title%> </td>
  <td class="filterable-cell"><%= politician.email%></td>
  <td class="filterable-cell"><%= link_to 'More info', politician%></td>
  <td class="filterable-cell"><%= link_to 'Edit', edit_politician_path(politician)%></td>
  <td class="filterable-cell"><%= link_to 'Restore', politician, method: :restore, data: { confirm: 'Are you sure?' }%></td>
</tr>

<%end%>
  </table>
  </div>

app/views/politicians/new.html.erb
<h1>New Politician</h1>

<%= render 'form', politician: @politician %>

<%= link_to 'Back', politicians_path %>

app/views/politicians/show.html.erb
<div class="container">
  <%if !@politician.deleted_at.blank? %>
  <h1 class="deleted_alert"> This States member was deleted on <%=@politician.deleted_at.strftime("%d %b. %Y")%> and is currently inactive </h1>
  <% end %>
  <div class="row">
    <div class="person_wraper col">
       <div class="card" style="width: 320px;">
          <img class="card-img-top" src="<%= @politician.avatar %>" alt="<%= @politician.title %> <%= @politician.full_name %>">
          <div class="card-body">
             <h4 class="card-title"><%= @politician.full_name %></h4>
             <p class="card-text"><%= @politician.summary %></p>
          </div>
          <ul class="list-group list-group-flush">
             <li class="list-group-item"><%== @politician.address %></li>
             <li class="list-group-item">Represents <%= @politician.parish.name %></li>

          </ul>
          <div class="card-body">
             <a href="#" class="card-link"><%= mail_to @politician.email, "Send Email", class: 'btn btn-primary' %></a>
             <a  class="card-link">
             <% if (@politician.landline) %>
             <%= link_to "Phone", "tel:#{@politician.landline}", class: 'btn btn-primary' %></a>
             <% elsif (@politician.mobile) %>
             <%= link_to "Phone", "tel:#{@politician.mobile}", class: 'btn btn-primary' %></a>
             <% elsif (@politician.fax) %>
             <%= link_to "Fax", "tel:#{@politician.Fax}", class: 'btn btn-primary' %></a>
             <% end %>

             <% if !current_user.blank? && current_user.role_id == 1 %>
             <br><br>
              <%= link_to 'Edit', edit_politician_path(@politician),class:"btn btn-primary manage_button" %>
                <%if @politician.deleted_at.blank? %>
                  <%= link_to 'Delete', @politician, type: :normal, method: :destroy, data: { confirm: 'Are you sure?' }, class:"btn btn-primary manage_button" %>
                    <%else%>
                    <%= link_to 'Undelete', @politician, method: :restore, class: 'btn' %>

                  <%end%>

              <%end%>
          </div>
       </div>
    </div>
    <div class="person_wraper_chart col">
       <script type="text/javascript">
          google.charts.load('current', {'packages':['corechart']});
          google.charts.setOnLoadCallback(drawChart);

          function drawChart() {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Vote Status');
            data.addColumn('number', 'Count');
            data.addRows([
              ['Out of island', <%= @politician.votes.where(vote_type: 'Out of the island').count %>],
              ['Not present for vote', <%= @politician.votes.where(vote_type: 'Not present for vote').count %>],
              ['Pour', <%= @politician.votes.where(vote_type: 'Pour').count %>],
              ['Contre', <%= @politician.votes.where(vote_type: 'Contre').count %>],
              ['Unwell', <%= @politician.votes.where(vote_type: 'Ill').count %>],
            ]);
            var options = {'title':'Breakdown of <%= number_with_delimiter(@politician.votes.count) %> Votes','is3D': true};
           var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
            chart.draw(data, options);
          }
       </script>
       <% if (@politician.votes.count>0) %>
       <div id="chart_div"></div>
       <div class="panel">
          <h4>How <%= @politician.title %> <%= @politician.full_name %> has voted</h4>
          <ul class="vote-descriptions">

          <% @votes_pagination.each.reverse_each do |vote| %>
          <li>Voted for <b><%= vote.vote_type %></b> for <%= link_to vote.proposition_title.truncate_words(13), vote_path(vote.id) %></li>
          <% end %>
       </div>
       <div>
       <div class="page_info">
         <%= page_entries_info @votes_pagination %>
       </div>
       <div class="page_select">
         <%= will_paginate(@votes_pagination, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
       </div>
     </div>
       <% else %>
       <div class="panel">
          <h3><%= @politician.title %> <%= @politician.full_name %></h3>
          <h5>This member has no vote</h5>
       </div>
       <% end %>
    </div>
  </div>